print ('What is your name?')
name = input('Enter your name: ')
print ('You entered: ', name)
print ('What is your age?')
age = int(input('Enter your age: '))
print ('You entered: ', age)
print ('What is your location?')
location = input('Enter your location: ')
print ('You entered: ', location)
print ('Hello ', name, 'you are ', age, 'years old and you live in ', location)
